language: node_js
node_js:
  - "8"
  - "6"
  - "4"
before_script:
  - 'if [ -n "${REACT-}" ] && [ "${TEST-}" = true ]; then sh install-relevant-react.sh && npm ls >/dev/null; fi'
script:
  - 'if [ -n "${LINT-}" ]; then npm run lint; fi'
  - 'if [ "${TEST-}" = true ]; then npm run test:only; fi'
env:
  global:
    - TEST=true
  matrix:
    - REACT=0.14
    - REACT=15.4
    - REACT=15
sudo: false
matrix:
  fast_finish: true
  include:
      env: LINT=true TEST=false
